//Make some arrays of objects based on the schema design

//Users
const users = [
  {
    id: 1,
    first_name: "Francis",
    last_name: "O'Tierney",
    email: "fotierney0@myspace.com",
    gender: "Male",
    password: "wX9)Pv7xtKm/6",
    location: "36210",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Brewton-Parker College",
    education_level: "college senior",
    classes: ["Art"],
    availibility: "Wednesday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Psychology",
    dob: "11/4/1996",
    work: "Sales Representative",
  },
  {
    id: 2,
    first_name: "Ema",
    last_name: "O' Hern",
    email: "eohern1@wsj.com",
    gender: "Female",
    password: "zP6(mu#h_\\",
    location: "4346",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Heisei International University",
    education_level: "college senior",
    classes: ["Science"],
    availibility: "Wednesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Biology",
    dob: "2/25/1995",
    work: "Recruiting Manager",
  },
  {
    id: 3,
    first_name: "Blinny",
    last_name: "Nare",
    email: "bnare2@slashdot.org",
    gender: "Female",
    password: "zZ5=}/G<R",
    location: "4485-174",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Universidade Federal de Uberlândia",
    education_level: "other",
    classes: ["English"],
    availibility: "Saturday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Computer Science",
    dob: "9/25/1984",
    work: null,
  },
  {
    id: 4,
    first_name: "Sophie",
    last_name: "Maystone",
    email: "smaystone3@prweb.com",
    gender: "Female",
    password: "uH4$b>zOg}@k\\",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Izhevsk State Technical University",
    education_level: "phD",
    classes: ["English"],
    availibility: "Wednesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Biology",
    dob: "12/20/2005",
    work: null,
  },
  {
    id: 5,
    first_name: "Gnni",
    last_name: "Dever",
    email: "gdever4@oaic.gov.au",
    gender: "Female",
    password: "kR1|({92{*",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Tibet University of Nationalities",
    education_level: "highschool",
    classes: ["Math"],
    availibility: "Sunday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Engineering",
    dob: "10/1/1996",
    work: null,
  },
  {
    id: 6,
    first_name: "Tome",
    last_name: "Noriega",
    email: "tnoriega5@hugedomains.com",
    gender: "Male",
    password: 'sL5*rR<"',
    location: "8309",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Tiraspol State University",
    education_level: "college sophomore",
    classes: ["English"],
    availibility: "Tuesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "Business Administration",
    dob: "8/31/2001",
    work: null,
  },
  {
    id: 7,
    first_name: "Fons",
    last_name: "Gingles",
    email: "fgingles6@amazonaws.com",
    gender: "Male",
    password: "cL1)1hU?.K",
    location: "58278-000",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "West Virginia University",
    education_level: "college junior",
    classes: ["History"],
    availibility: "Wednesday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "Business Administration",
    dob: "3/13/2002",
    work: "Chemical Engineer",
  },
  {
    id: 8,
    first_name: "Legra",
    last_name: "Feldheim",
    email: "lfeldheim7@nasa.gov",
    gender: "Female",
    password: "vJ4$Hl!sWW~\\m4l",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "International School of New Media, University of Lübeck",
    education_level: "phD",
    classes: ["History"],
    availibility: "Monday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Business Administration",
    dob: "6/5/1997",
    work: null,
  },
  {
    id: 9,
    first_name: "Napoleon",
    last_name: "Fitchew",
    email: "nfitchew8@usgs.gov",
    gender: "Male",
    password: "qS7_}w|JXS",
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Nyack College",
    education_level: "college sophomore",
    classes: ["English"],
    availibility: "Friday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English", "German"],
    study_habits: "committed studying",
    major: "English Literature",
    dob: "8/12/2001",
    work: "Programmer Analyst IV",
  },
  {
    id: 10,
    first_name: "Ashbey",
    last_name: "Pattrick",
    email: "apattrick9@netvibes.com",
    gender: "Male",
    password: "rL8`@AX7?Ijg(v",
    location: "01234",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Sudan Academy of Sciences",
    education_level: "other",
    classes: ["Math"],
    availibility: "Sunday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "English Literature",
    dob: "4/29/1990",
    work: null,
  },
  {
    id: 11,
    first_name: "Drusie",
    last_name: "Mungane",
    email: "dmunganea@cam.ac.uk",
    gender: "Female",
    password: "sQ2+Pi!uqEGPJLv",
    location: "24011",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Kafkas University",
    education_level: "phD",
    classes: ["History"],
    availibility: "Monday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English", "Japanese"],
    study_habits: "semi-relaxed",
    major: "Art History",
    dob: "3/19/1986",
    work: "Food Chemist",
  },
  {
    id: 12,
    first_name: "Franchot",
    last_name: "McKinty",
    email: "fmckintyb@youtube.com",
    gender: "Genderqueer",
    password: "dY1&pQ9b?xB,gH6",
    location: "37129",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Asa University Bangladesh",
    education_level: "phD",
    classes: ["History"],
    availibility: "Sunday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Biology",
    dob: "8/13/1983",
    work: null,
  },
  {
    id: 13,
    first_name: "Arly",
    last_name: "Furlong",
    email: "afurlongc@icq.com",
    gender: "Female",
    password: "sL1?(v\\|W+wQ<",
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Universidad de Puerto Rico, Cayey",
    education_level: "other",
    classes: ["Math"],
    availibility: "Wednesday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "English Literature",
    dob: "9/7/1986",
    work: null,
  },
  {
    id: 14,
    first_name: "Eleni",
    last_name: "Eglinton",
    email: "eeglintond@fema.gov",
    gender: "Female",
    password: "rO9>c.au",
    location: "N37",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "UNESCO-IHE Institute for Water Education",
    education_level: "college junior",
    classes: ["History"],
    availibility: "Tuesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Engineering",
    dob: "7/21/1999",
    work: null,
  },
  {
    id: 15,
    first_name: "Lexi",
    last_name: "Anthonies",
    email: "lanthoniese@cargocollective.com",
    gender: "Female",
    password: "aK5/?NAI2vAV'I",
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Université de Toulouse-le-Mirail (Toulouse II)",
    education_level: "highschool",
    classes: ["History"],
    availibility: "Wednesday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Biology",
    dob: "12/15/1986",
    work: null,
  },
  {
    id: 16,
    first_name: "Sherlocke",
    last_name: "Repp",
    email: "sreppf@pagesperso-orange.fr",
    gender: "Male",
    password: "hW7$=9O&`&h'.Z",
    location: "01234",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Laurus Technical Institute",
    education_level: "college sophomore",
    classes: ["English"],
    availibility: "Friday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English", "Spanish"],
    study_habits: "grinding studying",
    major: "Business Administration",
    dob: "2/10/1981",
    work: null,
  },
  {
    id: 17,
    first_name: "Lewiss",
    last_name: "Banishevitz",
    email: "lbanishevitzg@godaddy.com",
    gender: "Male",
    password: "bV3'#xv\\#EB(?1",
    location: "1433",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Sami Shamoon College of Engineering",
    education_level: "college sophomore",
    classes: ["Math"],
    availibility: "Sunday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "English Literature",
    dob: "1/6/1992",
    work: null,
  },
  {
    id: 18,
    first_name: "Heriberto",
    last_name: "Fevier",
    email: "hfevierh@squarespace.com",
    gender: "Male",
    password: "jI7_s('Z.IJ`,Nz",
    location: "T1K",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "LICCSAL Business College",
    education_level: "other",
    classes: ["Art"],
    availibility: "Saturday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "English Literature",
    dob: "3/21/1993",
    work: null,
  },
  {
    id: 19,
    first_name: "Bordy",
    last_name: "Davey",
    email: "bdaveyi@pcworld.com",
    gender: "Male",
    password: "eJ3|feA+\\6",
    location: "82104 CEDEX",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Banat's University of Agricultural Sciences",
    education_level: "college junior",
    classes: ["History"],
    availibility: "Sunday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "English Literature",
    dob: "7/13/2000",
    work: null,
  },
  {
    id: 20,
    first_name: "Carmelina",
    last_name: "Cathersides",
    email: "ccathersidesj@acquirethisname.com",
    gender: "Female",
    password: "xO6~'g5u`esHp`T",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Vellore Institute of Technology",
    education_level: "phD",
    classes: ["Art"],
    availibility: "Tuesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Business Administration",
    dob: "10/21/1989",
    work: null,
  },
  {
    id: 21,
    first_name: "Bradly",
    last_name: "Guidotti",
    email: "bguidottik@ihg.com",
    gender: "Genderfluid",
    password: "nX0{+WS7yWf3V{=e",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Universidad Nacional Pedro Henríquez Ureña",
    education_level: "college freshman",
    classes: ["History"],
    availibility: "Tuesday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Biology",
    dob: "11/13/1989",
    work: null,
  },
  {
    id: 22,
    first_name: "Elianora",
    last_name: "Pasfield",
    email: "epasfieldl@rakuten.co.jp",
    gender: "Bigender",
    password: "vT9\\6K&#JEzIg",
    location: "4111",
    skills: ["Steam Turbines"],
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Rider University",
    education_level: "highschool",
    classes: ["History"],
    availibility: "Tuesday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "Engineering",
    dob: "2/15/2002",
    work: "Help Desk Technician",
  },
  {
    id: 23,
    first_name: "Don",
    last_name: "McLoughlin",
    email: "dmcloughlinm@free.fr",
    gender: "Male",
    password: "tT2)(e>cXX",
    location: "06730-000",
    skills: ["Voice Over"],
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Universidad Autónoma de Veracruz Villa Rica",
    education_level: "college senior",
    classes: ["English"],
    availibility: "Sunday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "English Literature",
    dob: "9/14/1989",
    work: null,
  },
  {
    id: 24,
    first_name: "Darsey",
    last_name: "Simonel",
    email: "dsimoneln@i2i.jp",
    gender: "Female",
    password: "gW8<ez%,sIJ5XOk|",
    location: "01234",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Universidad Interamericana de Puerto Rico, Bayamón",
    education_level: "college senior",
    classes: ["Art"],
    availibility: "Wednesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Art History",
    dob: "8/1/1998",
    work: "Registered Nurse",
  },
  {
    id: 25,
    first_name: "Lelia",
    last_name: "Iddenden",
    email: "liddendeno@hp.com",
    gender: "Female",
    password: "oR0|YGNi/dVM,Z",
    location: "2630",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Ecole Nationale Supérieure de Physique de Grenoble",
    education_level: "college freshman",
    classes: ["History"],
    availibility: "Wednesday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "Biology",
    dob: "7/10/2001",
    work: null,
  },
  {
    id: 26,
    first_name: "Jaclin",
    last_name: "Boman",
    email: "jbomanp@ameblo.jp",
    gender: "Female",
    password: "aL5\\3yeTAm",
    location: "6550",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Technical University of Varna",
    education_level: "college sophomore",
    classes: ["Science"],
    availibility: "Monday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Business Administration",
    dob: "6/12/1984",
    work: null,
  },
  {
    id: 27,
    first_name: "Thadeus",
    last_name: "Soreau",
    email: "tsoreauq@shutterfly.com",
    gender: "Male",
    password: "wL0%0zkDmlhveIw",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Centro de Estudios Universitarios Xochicalco",
    education_level: "college freshman",
    classes: ["Math"],
    availibility: "Friday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Computer Science",
    dob: "1/14/2001",
    work: null,
  },
  {
    id: 28,
    first_name: "Willard",
    last_name: "Birdwhistle",
    email: "wbirdwhistler@themeforest.net",
    gender: "Male",
    password: "iE9~E|YYok",
    location: "38944 CEDEX",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "University of Insubria",
    education_level: "masters",
    classes: ["History"],
    availibility: "Friday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English", "Polish"],
    study_habits: "relaxed",
    major: "Engineering",
    dob: "12/19/1994",
    work: null,
  },
  {
    id: 29,
    first_name: "Ferdie",
    last_name: "Collingwood",
    email: "fcollingwoods@senate.gov",
    gender: "Male",
    password: "mC7~H{}7\\{I\\V",
    location: "01234",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Manuel S. Enverga University Foundation",
    education_level: "phD",
    classes: ["Art"],
    availibility: "Friday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Art History",
    dob: "5/22/1990",
    work: null,
  },
  {
    id: 30,
    first_name: "Reuven",
    last_name: "Szachniewicz",
    email: "rszachniewiczt@webmd.com",
    gender: "Male",
    password: "dJ0`(2!'Z`!syn`/",
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "ICT College",
    education_level: "college senior",
    classes: ["Science"],
    availibility: "Sunday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Psychology",
    dob: "2/8/1985",
    work: null,
  },
  {
    id: 31,
    first_name: "Heda",
    last_name: "Grandisson",
    email: "hgrandissonu@sbwire.com",
    gender: "Female",
    password: "gV7~ge)5?",
    location: "01234",
    skills: ["Voice Over"],
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Fachhochschulstudiengänge Krems IMC",
    education_level: "college senior",
    classes: ["History"],
    availibility: "Monday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Business Administration",
    dob: "12/31/1981",
    work: null,
  },
  {
    id: 32,
    first_name: "Archibald",
    last_name: "Woodward",
    email: "awoodwardv@tripod.com",
    gender: "Male",
    password: "mM7\\5ax8QVQW",
    location: "6526",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Universidad Catolica de La Santísima Concepción",
    education_level: "masters",
    classes: ["History"],
    availibility: "Friday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Biology",
    dob: "3/8/1982",
    work: null,
  },
  {
    id: 33,
    first_name: "Sheena",
    last_name: "Aspray",
    email: "sasprayw@indiegogo.com",
    gender: "Female",
    password: "bL8|Z#_Dyv8Fni",
    location: "18130",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Universitas Atma Jaya Yogyakarta",
    education_level: "college freshman",
    classes: ["Art"],
    availibility: "Monday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Engineering",
    dob: "12/7/2000",
    work: null,
  },
  {
    id: 34,
    first_name: "Haywood",
    last_name: "Keave",
    email: "hkeavex@eventbrite.com",
    gender: "Male",
    password: "jD6*W+{pby",
    location: "01234",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Dav University",
    education_level: "college freshman",
    classes: ["Math"],
    availibility: "Saturday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "Psychology",
    dob: "10/19/2003",
    work: null,
  },
  {
    id: 35,
    first_name: "Hilton",
    last_name: "Renshall",
    email: "hrenshally@wikimedia.org",
    gender: "Male",
    password: "qO4/2A`~k`&eYX_",
    location: "01234",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "St. Francis Xavier University",
    education_level: "college junior",
    classes: ["Math"],
    availibility: "Tuesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Biology",
    dob: "11/21/1999",
    work: null,
  },
  {
    id: 36,
    first_name: "Lucilia",
    last_name: "Reisen",
    email: "lreisenz@moonfruit.com",
    gender: "Female",
    password: 'zA8"MX*hP',
    location: "68105",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Rhodes University",
    education_level: "college junior",
    classes: ["History"],
    availibility: "Friday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Business Administration",
    dob: "10/1/1999",
    work: null,
  },
  {
    id: 37,
    first_name: "Albertina",
    last_name: "Pippin",
    email: "apippin10@yellowbook.com",
    gender: "Bigender",
    password: "iF7.7?e1",
    location: "4801",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "New York Law School",
    education_level: "other",
    classes: ["English"],
    availibility: "Friday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Computer Science",
    dob: "2/21/1999",
    work: null,
  },
  {
    id: 38,
    first_name: "Kimbell",
    last_name: "Weale",
    email: "kweale11@paypal.com",
    gender: "Male",
    password: "aM8{T~i5UjqY44",
    location: "6594",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Shanghai Business School",
    education_level: "college senior",
    classes: ["English"],
    availibility: "Wednesday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Biology",
    dob: "9/16/1991",
    work: "Developer II",
  },
  {
    id: 39,
    first_name: "Giustino",
    last_name: "Beaushaw",
    email: "gbeaushaw12@chicagotribune.com",
    gender: "Male",
    password: 'qQ7#"ncS*cU~4&',
    location: "01234",
    about_me: "I enjoy exploring new subjects and expanding my knowledge.",
    education: "Gandhi Institute of Technology and Managment",
    education_level: "other",
    classes: ["Math"],
    availibility: "Saturday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Biology",
    dob: "2/4/2000",
    work: "Pharmacist",
  },
  {
    id: 40,
    first_name: "Doroteya",
    last_name: "Ogden",
    email: "dogden13@tripod.com",
    gender: "Female",
    password: "bB2#HYfAiT/s",
    location: "01234",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Eurasia International University",
    education_level: "college sophomore",
    classes: ["Art"],
    availibility: "Sunday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Biology",
    dob: "3/9/1999",
    work: null,
  },
  {
    id: 41,
    first_name: "Loretta",
    last_name: "O' Neligan",
    email: "loneligan14@discuz.net",
    gender: "Female",
    password: "qV8>*YKo|}1VU",
    location: "6809",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "University of SV Cyril and Methodius in Trnava",
    education_level: "masters",
    classes: ["Art"],
    availibility: "Tuesday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "English Literature",
    dob: "12/2/1982",
    work: null,
  },
  {
    id: 42,
    first_name: "Tucky",
    last_name: "Roelofs",
    email: "troelofs15@pagesperso-orange.fr",
    gender: "Male",
    password: 'aB3#.Q"gdg%dP',
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Noakhali University of Science and Technology",
    education_level: "phD",
    classes: ["History"],
    availibility: "Sunday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "Psychology",
    dob: "3/4/1999",
    work: null,
  },
  {
    id: 43,
    first_name: "Kalli",
    last_name: "Stickens",
    email: "kstickens16@prlog.org",
    gender: "Female",
    password: "gL4)a2_xo",
    location: "01234",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Al-Zaytoonah University",
    education_level: "college junior",
    classes: ["History"],
    availibility: "Thursday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "relaxed",
    major: "English Literature",
    dob: "7/31/1981",
    work: null,
  },
  {
    id: 44,
    first_name: "Briano",
    last_name: "Getcliffe",
    email: "bgetcliffe17@jigsy.com",
    gender: "Male",
    password: "aN2`7*@SK",
    location: "01234",
    about_me:
      "I am a motivated learner who is always seeking opportunities for growth and improvement.",
    education: "Dayalbagh Educational Institute",
    education_level: "masters",
    classes: ["Art"],
    availibility: "Sunday",
    interests: ["cooking"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Art History",
    dob: "5/5/1987",
    work: null,
  },
  {
    id: 45,
    first_name: "Elfrida",
    last_name: "Barnham",
    email: "ebarnham18@smugmug.com",
    gender: "Genderqueer",
    password: "aL6,'3+@tjU",
    location: "833 24",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Anderson University",
    education_level: "college freshman",
    classes: ["Science"],
    availibility: "Friday",
    interests: ["traveling"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Biology",
    dob: "7/20/1998",
    work: null,
  },
  {
    id: 46,
    first_name: "Quent",
    last_name: "Beauman",
    email: "qbeauman19@youtu.be",
    gender: "Male",
    password: "wU9%cpR/6",
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Universitas Terbuka Indonesia",
    education_level: "college freshman",
    classes: ["Math"],
    availibility: "Tuesday",
    interests: ["gardening"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "Business Administration",
    dob: "7/31/1999",
    work: "Database Administrator IV",
  },
  {
    id: 47,
    first_name: "Boigie",
    last_name: "Masse",
    email: "bmasse1a@myspace.com",
    gender: "Male",
    password: "qP8,o|2rG=h",
    location: "01234",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: 'Music Academy "Karol Lipinski" in Wroclaw',
    education_level: "other",
    classes: ["English"],
    availibility: "Saturday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Biology",
    dob: "4/15/2004",
    work: "Quality Engineer",
  },
  {
    id: 48,
    first_name: "Derek",
    last_name: "Dommersen",
    email: "ddommersen1b@archive.org",
    gender: "Male",
    password: "xK9>(Vr*IV0=j=3",
    location: "5631",
    about_me:
      "I strive for academic excellence and am always eager to take on new challenges.",
    education: "Azerbaijan State Oil Academy",
    education_level: "college junior",
    classes: ["History"],
    availibility: "Thursday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "grinding studying",
    major: "Engineering",
    dob: "7/28/1991",
    work: null,
  },
  {
    id: 49,
    first_name: "Ginger",
    last_name: "Espadate",
    email: "gespadate1c@live.com",
    gender: "Polygender",
    password: 'lM8@vk"FFFv',
    location: "5110",
    about_me:
      "I am an active participant in class discussions and enjoy collaborating with my peers.",
    education: "Tokoha Gakuen University",
    education_level: "college junior",
    classes: ["Art"],
    availibility: "Thursday",
    interests: ["reading"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "semi-relaxed",
    major: "Art History",
    dob: "5/2/1986",
    work: "Nurse Practicioner",
  },
  {
    id: 50,
    first_name: "Willis",
    last_name: "Sautter",
    email: "wsautter1d@ed.gov",
    gender: "Male",
    password: "oR3'*=6Y,e",
    location: "01234",
    about_me: "I am a dedicated student with a passion for learning.",
    education: "Korea Advanced Institute of Science & Technology",
    education_level: "masters",
    classes: ["Math"],
    availibility: "Thursday",
    interests: ["painting"],
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/1200px-Default_pfp.svg.png",
    languages: ["English"],
    study_habits: "committed studying",
    major: "English Literature",
    dob: "2/18/1999",
    work: "Software Consultant",
  },
];

//Events
const events = [
  {
    id: 1,
    title: "Chemistry 101 Lab Buddies",
    description:
      "Our study group is dedicated to exploring the fascinating world of art and creativity. We will delve into different art movements",
    location: "54321",
    datetime: "4/4/2024",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "10/3/2023",
    topic: "Physical Education",
    duration: 220,
    gender: "Male",
    group: true,
  },
  {
    id: 2,
    title: "Mathematics 301 Discussion",
    description: "analyze famous artworks",
    location: "12345",
    datetime: "11/6/2023",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "9/29/2023",
    topic: "Math",
    duration: 237,
    gender: "Female",
    group: false,
  },
  {
    id: 3,
    title: "Chemistry 101 Lab Buddies",
    description: "gain new perspectives",
    location: "54321",
    datetime: "4/6/2024",
    virtual: true,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "9/21/2023",
    topic: "Art",
    duration: 105,
    gender: null,
    group: true,
  },
  {
    id: 4,
    title: "Biology 102 Research Team",
    description: "gain new perspectives",
    location: "virtual",
    datetime: "9/23/2023",
    virtual: true,
    comments: "Counting down the days until the event!",
    created_at: "10/4/2023",
    topic: "Art",
    duration: 61,
    gender: "Male",
    group: false,
  },
  {
    id: 5,
    title: "Mathematics 301 Discussion",
    description:
      "The study group is a collaborative space where members can come together to discuss various topics and share their knowledge. We will cover a wide range of subjects including literature",
    location: "98765",
    datetime: "3/28/2024",
    virtual: false,
    comments: "This event is going to be amazing!",
    created_at: "10/14/2023",
    topic: "Art",
    duration: 145,
    gender: null,
    group: true,
  },
  {
    id: 6,
    title: "Physics 201 Study Group",
    description: "analyze famous artworks",
    location: "54321",
    datetime: "8/10/2024",
    virtual: false,
    comments: "This event is going to be amazing!",
    created_at: "9/28/2023",
    topic: "Art",
    duration: 181,
    gender: null,
    group: true,
  },
  {
    id: 7,
    title: "Biology 102 Research Team",
    description: "science",
    location: "54321",
    datetime: "8/21/2024",
    virtual: true,
    comments: "I can't wait to attend!",
    created_at: "10/7/2023",
    topic: "Science",
    duration: 111,
    gender: null,
    group: false,
  },
  {
    id: 8,
    title: "Chemistry 101 Lab Buddies",
    description:
      "and discuss the impact of art on society. Whether you're an art enthusiast or just curious about the subject",
    location: "12345",
    datetime: "7/17/2024",
    virtual: false,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "10/14/2023",
    topic: "Art",
    duration: 82,
    gender: "Male",
    group: false,
  },
  {
    id: 9,
    title: "Chemistry 101 Lab Buddies",
    description:
      "The study group focuses on personal development and self-improvement. We will explore various strategies and techniques to enhance productivity",
    location: "virtual",
    datetime: "9/5/2024",
    virtual: false,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "10/2/2023",
    topic: "English",
    duration: 116,
    gender: null,
    group: false,
  },
  {
    id: 10,
    title: "Chemistry 101 Lab Buddies",
    description:
      "Our study group is dedicated to exploring the fascinating world of art and creativity. We will delve into different art movements",
    location: "98765",
    datetime: "3/4/2024",
    virtual: false,
    comments: "So excited for this event!",
    created_at: "10/13/2023",
    topic: "English",
    duration: 167,
    gender: "Male",
    group: false,
  },
  {
    id: 11,
    title: "Mathematics 301 Discussion",
    description:
      "The study group is a collaborative space where members can come together to discuss various topics and share their knowledge. We will cover a wide range of subjects including literature",
    location: "01234",
    datetime: "6/10/2024",
    virtual: false,
    comments: "So excited for this event!",
    created_at: "10/4/2023",
    topic: "History",
    duration: 179,
    gender: null,
    group: false,
  },
  {
    id: 12,
    title: "Mathematics 301 Discussion",
    description:
      "Our study group is dedicated to exploring the fascinating world of art and creativity. We will delve into different art movements",
    location: "98765",
    datetime: "1/18/2024",
    virtual: false,
    comments: "So excited for this event!",
    created_at: "10/11/2023",
    topic: "Math",
    duration: 177,
    gender: null,
    group: false,
  },
  {
    id: 13,
    title: "Biology 102 Research Team",
    description:
      "The study group is a collaborative space where members can come together to discuss various topics and share their knowledge. We will cover a wide range of subjects including literature",
    location: "67890",
    datetime: "2/24/2024",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "10/3/2023",
    topic: "History",
    duration: 124,
    gender: null,
    group: false,
  },
  {
    id: 14,
    title: "Physics 201 Study Group",
    description: "gain new perspectives",
    location: "virtual",
    datetime: "6/29/2024",
    virtual: true,
    comments: "Counting down the days until the event!",
    created_at: "10/3/2023",
    topic: "Physical Education",
    duration: 104,
    gender: null,
    group: true,
  },
  {
    id: 15,
    title: "Biology 102 Research Team",
    description: "analyze famous artworks",
    location: "12345",
    datetime: "7/30/2024",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "10/3/2023",
    topic: "Math",
    duration: 73,
    gender: null,
    group: true,
  },
  {
    id: 16,
    title: "Chemistry 101 Lab Buddies",
    description: "and expand your knowledge.",
    location: "67890",
    datetime: "9/28/2023",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "9/25/2023",
    topic: "English",
    duration: 138,
    gender: null,
    group: true,
  },
  {
    id: 17,
    title: "Computer Science 202 Coding Club",
    description: "gain new perspectives",
    location: "virtual",
    datetime: "9/1/2024",
    virtual: true,
    comments: "This event is going to be amazing!",
    created_at: "10/2/2023",
    topic: "Math",
    duration: 117,
    gender: null,
    group: true,
  },
  {
    id: 18,
    title: "Physics 201 Study Group",
    description:
      "this group welcomes all levels of knowledge and encourages lively conversations. Come join us to discover the beauty and inspiration that art brings to our lives.",
    location: "54321",
    datetime: "7/12/2024",
    virtual: true,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "10/12/2023",
    topic: "English",
    duration: 230,
    gender: null,
    group: true,
  },
  {
    id: 19,
    title: "Physics 201 Study Group",
    description: "gain new perspectives",
    location: "98765",
    datetime: "11/29/2023",
    virtual: false,
    comments: "So excited for this event!",
    created_at: "9/30/2023",
    topic: "History",
    duration: 205,
    gender: null,
    group: false,
  },
  {
    id: 20,
    title: "Mathematics 301 Discussion",
    description: "history",
    location: "54321",
    datetime: "6/1/2024",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "9/29/2023",
    topic: "Physical Education",
    duration: 175,
    gender: null,
    group: false,
  },
  {
    id: 21,
    title: "Mathematics 301 Discussion",
    description:
      "The study group is a collaborative space where members can come together to discuss various topics and share their knowledge. We will cover a wide range of subjects including literature",
    location: "67890",
    datetime: "9/23/2023",
    virtual: false,
    comments: "So excited for this event!",
    created_at: "10/10/2023",
    topic: "English",
    duration: 60,
    gender: null,
    group: false,
  },
  {
    id: 22,
    title: "Biology 102 Research Team",
    description:
      "Our study group is dedicated to exploring the fascinating world of art and creativity. We will delve into different art movements",
    location: "12345",
    datetime: "9/4/2024",
    virtual: true,
    comments: "I can't wait to attend!",
    created_at: "10/13/2023",
    topic: "Physical Education",
    duration: 115,
    gender: null,
    group: false,
  },
  {
    id: 23,
    title: "Chemistry 101 Lab Buddies",
    description:
      "and more. The group encourages active participation and open-mindedness",
    location: "67890",
    datetime: "4/26/2024",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "9/23/2023",
    topic: "Science",
    duration: 198,
    gender: "Male",
    group: false,
  },
  {
    id: 24,
    title: "Biology 102 Research Team",
    description: "history",
    location: "virtual",
    datetime: "8/6/2024",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "10/2/2023",
    topic: "Art",
    duration: 127,
    gender: null,
    group: true,
  },
  {
    id: 25,
    title: "Chemistry 101 Lab Buddies",
    description: "history",
    location: "12345",
    datetime: "2/14/2024",
    virtual: false,
    comments: "This event is going to be amazing!",
    created_at: "9/26/2023",
    topic: "History",
    duration: 86,
    gender: null,
    group: false,
  },
  {
    id: 26,
    title: "Chemistry 101 Lab Buddies",
    description: "history",
    location: "virtual",
    datetime: "10/4/2023",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "9/26/2023",
    topic: "Physical Education",
    duration: 127,
    gender: null,
    group: true,
  },
  {
    id: 27,
    title: "Computer Science 202 Coding Club",
    description:
      "and overcome challenges. Through interactive sessions and shared experiences",
    location: "67890",
    datetime: "12/10/2023",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "10/8/2023",
    topic: "Physical Education",
    duration: 218,
    gender: "Male",
    group: false,
  },
  {
    id: 28,
    title: "Chemistry 101 Lab Buddies",
    description: "and expand your knowledge.",
    location: "12345",
    datetime: "11/14/2023",
    virtual: false,
    comments: "This event is going to be amazing!",
    created_at: "9/29/2023",
    topic: "Math",
    duration: 142,
    gender: "Female",
    group: true,
  },
  {
    id: 29,
    title: "Physics 201 Study Group",
    description: "manage time effectively",
    location: "12345",
    datetime: "11/7/2023",
    virtual: false,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "10/3/2023",
    topic: "Science",
    duration: 181,
    gender: null,
    group: false,
  },
  {
    id: 30,
    title: "Chemistry 101 Lab Buddies",
    description: "gain new perspectives",
    location: "virtual",
    datetime: "3/13/2024",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "10/12/2023",
    topic: "English",
    duration: 168,
    gender: null,
    group: false,
  },
  {
    id: 31,
    title: "Physics 201 Study Group",
    description: "history",
    location: "12345",
    datetime: "11/25/2023",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "10/10/2023",
    topic: "History",
    duration: 203,
    gender: null,
    group: true,
  },
  {
    id: 32,
    title: "Mathematics 301 Discussion",
    description:
      "and discuss the impact of art on society. Whether you're an art enthusiast or just curious about the subject",
    location: "98765",
    datetime: "2/28/2024",
    virtual: true,
    comments: "I can't wait to attend!",
    created_at: "10/2/2023",
    topic: "Physical Education",
    duration: 76,
    gender: "Male",
    group: true,
  },
  {
    id: 33,
    title: "Mathematics 301 Discussion",
    description:
      "fostering a supportive environment for learning and growth. Join us to engage in stimulating discussions",
    location: "virtual",
    datetime: "3/9/2024",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "9/21/2023",
    topic: "Physical Education",
    duration: 204,
    gender: null,
    group: true,
  },
  {
    id: 34,
    title: "Mathematics 301 Discussion",
    description:
      "Our study group is dedicated to exploring the fascinating world of art and creativity. We will delve into different art movements",
    location: "67890",
    datetime: "12/8/2023",
    virtual: false,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "10/19/2023",
    topic: "Physical Education",
    duration: 65,
    gender: null,
    group: true,
  },
  {
    id: 35,
    title: "Mathematics 301 Discussion",
    description:
      "The study group is a collaborative space where members can come together to discuss various topics and share their knowledge. We will cover a wide range of subjects including literature",
    location: "virtual",
    datetime: "4/2/2024",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "10/17/2023",
    topic: "Art",
    duration: 62,
    gender: null,
    group: false,
  },
  {
    id: 36,
    title: "Mathematics 301 Discussion",
    description:
      "and discuss the impact of art on society. Whether you're an art enthusiast or just curious about the subject",
    location: "67890",
    datetime: "11/13/2023",
    virtual: true,
    comments: "Counting down the days until the event!",
    created_at: "10/19/2023",
    topic: "English",
    duration: 223,
    gender: null,
    group: false,
  },
  {
    id: 37,
    title: "Mathematics 301 Discussion",
    description: "manage time effectively",
    location: "01234",
    datetime: "1/2/2024",
    virtual: true,
    comments: "Counting down the days until the event!",
    created_at: "10/16/2023",
    topic: "English",
    duration: 161,
    gender: null,
    group: false,
  },
  {
    id: 38,
    title: "Biology 102 Research Team",
    description:
      "The study group is a collaborative space where members can come together to discuss various topics and share their knowledge. We will cover a wide range of subjects including literature",
    location: "virtual",
    datetime: "2/28/2024",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "10/2/2023",
    topic: "Physical Education",
    duration: 114,
    gender: null,
    group: false,
  },
  {
    id: 39,
    title: "Biology 102 Research Team",
    description:
      "and overcome challenges. Through interactive sessions and shared experiences",
    location: "virtual",
    datetime: "10/27/2023",
    virtual: true,
    comments: "This event is going to be amazing!",
    created_at: "10/13/2023",
    topic: "History",
    duration: 68,
    gender: null,
    group: true,
  },
  {
    id: 40,
    title: "Chemistry 101 Lab Buddies",
    description: "history",
    location: "54321",
    datetime: "2/6/2024",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "9/21/2023",
    topic: "Physical Education",
    duration: 211,
    gender: null,
    group: true,
  },
  {
    id: 41,
    title: "Chemistry 101 Lab Buddies",
    description: "gain new perspectives",
    location: "virtual",
    datetime: "4/26/2024",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "9/25/2023",
    topic: "Art",
    duration: 96,
    gender: null,
    group: true,
  },
  {
    id: 42,
    title: "Chemistry 101 Lab Buddies",
    description:
      "fostering a supportive environment for learning and growth. Join us to engage in stimulating discussions",
    location: "67890",
    datetime: "5/12/2024",
    virtual: false,
    comments: "I'm thrilled to be a part of this event!",
    created_at: "10/6/2023",
    topic: "Math",
    duration: 125,
    gender: null,
    group: false,
  },
  {
    id: 43,
    title: "Physics 201 Study Group",
    description:
      "this group welcomes all levels of knowledge and encourages lively conversations. Come join us to discover the beauty and inspiration that art brings to our lives.",
    location: "98765",
    datetime: "11/1/2023",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "9/24/2023",
    topic: "Physical Education",
    duration: 128,
    gender: null,
    group: true,
  },
  {
    id: 44,
    title: "Mathematics 301 Discussion",
    description: "manage time effectively",
    location: "virtual",
    datetime: "3/11/2024",
    virtual: false,
    comments: "This event is going to be amazing!",
    created_at: "10/15/2023",
    topic: "Art",
    duration: 184,
    gender: null,
    group: false,
  },
  {
    id: 45,
    title: "Chemistry 101 Lab Buddies",
    description:
      "and more. The group encourages active participation and open-mindedness",
    location: "virtual",
    datetime: "6/7/2024",
    virtual: true,
    comments: "So excited for this event!",
    created_at: "10/14/2023",
    topic: "Math",
    duration: 194,
    gender: null,
    group: false,
  },
  {
    id: 46,
    title: "Computer Science 202 Coding Club",
    description:
      "Our study group is dedicated to exploring the fascinating world of art and creativity. We will delve into different art movements",
    location: "67890",
    datetime: "9/11/2024",
    virtual: true,
    comments: "Counting down the days until the event!",
    created_at: "9/29/2023",
    topic: "Art",
    duration: 94,
    gender: null,
    group: false,
  },
  {
    id: 47,
    title: "Mathematics 301 Discussion",
    description: "set goals",
    location: "98765",
    datetime: "8/14/2024",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "10/9/2023",
    topic: "History",
    duration: 75,
    gender: "Male",
    group: false,
  },
  {
    id: 48,
    title: "Mathematics 301 Discussion",
    description:
      "we aim to create a supportive community that empowers individuals to reach their full potential. Join us to embark on a journey of self-discovery and growth.",
    location: "54321",
    datetime: "2/13/2024",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "10/3/2023",
    topic: "Math",
    duration: 238,
    gender: "Male",
    group: false,
  },
  {
    id: 49,
    title: "Physics 201 Study Group",
    description:
      "fostering a supportive environment for learning and growth. Join us to engage in stimulating discussions",
    location: "54321",
    datetime: "4/20/2024",
    virtual: false,
    comments: "Counting down the days until the event!",
    created_at: "10/19/2023",
    topic: "Physical Education",
    duration: 178,
    gender: "Female",
    group: false,
  },
  {
    id: 50,
    title: "Mathematics 301 Discussion",
    description: "set goals",
    location: "12345",
    datetime: "3/5/2024",
    virtual: false,
    comments: "I can't wait to attend!",
    created_at: "10/13/2023",
    topic: "English",
    duration: 232,
    gender: null,
    group: true,
  },
];

//RSVPs
const rsvps = [
  { id: 1, event_id: 32, user_id: 14, rsvp_status: false },
  { id: 2, event_id: 3, user_id: 45, rsvp_status: true },
  { id: 3, event_id: 30, user_id: 3, rsvp_status: true },
  { id: 4, event_id: 30, user_id: 28, rsvp_status: true },
  { id: 5, event_id: 42, user_id: 12, rsvp_status: false },
  { id: 6, event_id: 35, user_id: 36, rsvp_status: true },
  { id: 7, event_id: 4, user_id: 2, rsvp_status: false },
  { id: 8, event_id: 27, user_id: 31, rsvp_status: false },
  { id: 9, event_id: 19, user_id: 9, rsvp_status: true },
  { id: 10, event_id: 19, user_id: 42, rsvp_status: false },
  { id: 11, event_id: 44, user_id: 46, rsvp_status: true },
  { id: 12, event_id: 28, user_id: 4, rsvp_status: true },
  { id: 13, event_id: 34, user_id: 48, rsvp_status: true },
  { id: 14, event_id: 11, user_id: 30, rsvp_status: true },
  { id: 15, event_id: 21, user_id: 11, rsvp_status: true },
  { id: 16, event_id: 36, user_id: 28, rsvp_status: true },
  { id: 17, event_id: 38, user_id: 46, rsvp_status: false },
  { id: 18, event_id: 9, user_id: 21, rsvp_status: false },
  { id: 19, event_id: 24, user_id: 45, rsvp_status: true },
  { id: 20, event_id: 28, user_id: 7, rsvp_status: false },
  { id: 21, event_id: 49, user_id: 15, rsvp_status: true },
  { id: 22, event_id: 22, user_id: 37, rsvp_status: false },
  { id: 23, event_id: 11, user_id: 4, rsvp_status: true },
  { id: 24, event_id: 47, user_id: 23, rsvp_status: false },
  { id: 25, event_id: 23, user_id: 2, rsvp_status: true },
  { id: 26, event_id: 26, user_id: 12, rsvp_status: false },
  { id: 27, event_id: 47, user_id: 45, rsvp_status: false },
  { id: 28, event_id: 39, user_id: 16, rsvp_status: false },
  { id: 29, event_id: 47, user_id: 48, rsvp_status: false },
  { id: 30, event_id: 8, user_id: 35, rsvp_status: true },
  { id: 31, event_id: 9, user_id: 29, rsvp_status: true },
  { id: 32, event_id: 44, user_id: 34, rsvp_status: true },
  { id: 33, event_id: 3, user_id: 22, rsvp_status: false },
  { id: 34, event_id: 35, user_id: 40, rsvp_status: true },
  { id: 35, event_id: 20, user_id: 32, rsvp_status: true },
  { id: 36, event_id: 23, user_id: 25, rsvp_status: false },
  { id: 37, event_id: 35, user_id: 10, rsvp_status: true },
  { id: 38, event_id: 7, user_id: 18, rsvp_status: true },
  { id: 39, event_id: 12, user_id: 10, rsvp_status: true },
  { id: 40, event_id: 42, user_id: 23, rsvp_status: false },
  { id: 41, event_id: 27, user_id: 38, rsvp_status: false },
  { id: 42, event_id: 3, user_id: 48, rsvp_status: false },
  { id: 43, event_id: 21, user_id: 46, rsvp_status: false },
  { id: 44, event_id: 8, user_id: 38, rsvp_status: false },
  { id: 45, event_id: 17, user_id: 44, rsvp_status: true },
  { id: 46, event_id: 31, user_id: 42, rsvp_status: true },
  { id: 47, event_id: 6, user_id: 18, rsvp_status: false },
  { id: 48, event_id: 24, user_id: 20, rsvp_status: false },
  { id: 49, event_id: 25, user_id: 4, rsvp_status: true },
  { id: 50, event_id: 24, user_id: 26, rsvp_status: true },
];

//Messages
const messages = [
  {
    id: 1,
    sender: 32,
    receiver: 30,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 42,
    created_at: "10/3/2023",
  },
  {
    id: 2,
    sender: 34,
    receiver: 38,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 36,
    created_at: "10/1/2023",
  },
  {
    id: 3,
    sender: 13,
    receiver: 49,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 31,
    created_at: "10/10/2023",
  },
  {
    id: 4,
    sender: 46,
    receiver: 4,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 49,
    created_at: "10/6/2023",
  },
  {
    id: 5,
    sender: 33,
    receiver: 27,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 9,
    created_at: "10/10/2023",
  },
  {
    id: 6,
    sender: 2,
    receiver: 46,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 13,
    created_at: "10/13/2023",
  },
  {
    id: 7,
    sender: 13,
    receiver: 25,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 14,
    created_at: "10/1/2023",
  },
  {
    id: 8,
    sender: 38,
    receiver: 31,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 19,
    created_at: "10/5/2023",
  },
  {
    id: 9,
    sender: 36,
    receiver: 23,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 50,
    created_at: "10/19/2023",
  },
  {
    id: 10,
    sender: 45,
    receiver: 48,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 34,
    created_at: "10/4/2023",
  },
  {
    id: 11,
    sender: 23,
    receiver: 33,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 26,
    created_at: "10/17/2023",
  },
  {
    id: 12,
    sender: 50,
    receiver: 8,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 45,
    created_at: "10/12/2023",
  },
  {
    id: 13,
    sender: 32,
    receiver: 15,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 12,
    created_at: "10/12/2023",
  },
  {
    id: 14,
    sender: 2,
    receiver: 43,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 22,
    created_at: "10/8/2023",
  },
  {
    id: 15,
    sender: 18,
    receiver: 20,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 29,
    created_at: "9/29/2023",
  },
  {
    id: 16,
    sender: 7,
    receiver: 10,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 46,
    created_at: "10/10/2023",
  },
  {
    id: 17,
    sender: 11,
    receiver: 17,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 17,
    created_at: "9/21/2023",
  },
  {
    id: 18,
    sender: 38,
    receiver: 31,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 9,
    created_at: "10/9/2023",
  },
  {
    id: 19,
    sender: 25,
    receiver: 26,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 16,
    created_at: "10/9/2023",
  },
  {
    id: 20,
    sender: 37,
    receiver: 43,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 44,
    created_at: "10/18/2023",
  },
  {
    id: 21,
    sender: 44,
    receiver: 10,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 18,
    created_at: "9/21/2023",
  },
  {
    id: 22,
    sender: 41,
    receiver: 18,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 2,
    created_at: "9/21/2023",
  },
  {
    id: 23,
    sender: 39,
    receiver: 33,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 18,
    created_at: "9/24/2023",
  },
  {
    id: 24,
    sender: 33,
    receiver: 5,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 19,
    created_at: "10/2/2023",
  },
  {
    id: 25,
    sender: 16,
    receiver: 20,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 14,
    created_at: "10/5/2023",
  },
  {
    id: 26,
    sender: 9,
    receiver: 45,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 29,
    created_at: "10/4/2023",
  },
  {
    id: 27,
    sender: 30,
    receiver: 11,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 24,
    created_at: "9/21/2023",
  },
  {
    id: 28,
    sender: 48,
    receiver: 45,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 18,
    created_at: "10/10/2023",
  },
  {
    id: 29,
    sender: 17,
    receiver: 34,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 14,
    created_at: "9/23/2023",
  },
  {
    id: 30,
    sender: 12,
    receiver: 5,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 22,
    created_at: "10/5/2023",
  },
  {
    id: 31,
    sender: 26,
    receiver: 11,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 32,
    created_at: "10/14/2023",
  },
  {
    id: 32,
    sender: 21,
    receiver: 39,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 13,
    created_at: "10/12/2023",
  },
  {
    id: 33,
    sender: 18,
    receiver: 32,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 27,
    created_at: "10/2/2023",
  },
  {
    id: 34,
    sender: 45,
    receiver: 9,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 15,
    created_at: "10/2/2023",
  },
  {
    id: 35,
    sender: 42,
    receiver: 12,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 41,
    created_at: "10/17/2023",
  },
  {
    id: 36,
    sender: 31,
    receiver: 13,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 14,
    created_at: "10/10/2023",
  },
  {
    id: 37,
    sender: 8,
    receiver: 39,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 43,
    created_at: "10/9/2023",
  },
  {
    id: 38,
    sender: 10,
    receiver: 33,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 37,
    created_at: "10/19/2023",
  },
  {
    id: 39,
    sender: 6,
    receiver: 31,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 17,
    created_at: "10/4/2023",
  },
  {
    id: 40,
    sender: 32,
    receiver: 47,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 39,
    created_at: "10/10/2023",
  },
  {
    id: 41,
    sender: 38,
    receiver: 46,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 45,
    created_at: "10/14/2023",
  },
  {
    id: 42,
    sender: 34,
    receiver: 12,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 44,
    created_at: "10/18/2023",
  },
  {
    id: 43,
    sender: 35,
    receiver: 17,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 41,
    created_at: "10/1/2023",
  },
  {
    id: 44,
    sender: 11,
    receiver: 3,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 41,
    created_at: "9/27/2023",
  },
  {
    id: 45,
    sender: 17,
    receiver: 35,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 16,
    created_at: "9/25/2023",
  },
  {
    id: 46,
    sender: 32,
    receiver: 45,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 15,
    created_at: "10/2/2023",
  },
  {
    id: 47,
    sender: 7,
    receiver: 14,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 27,
    created_at: "9/20/2023",
  },
  {
    id: 48,
    sender: 45,
    receiver: 33,
    message_content:
      "Let's collaborate on studying science. We can conduct experiments together and analyze the results.",
    thread_id: 7,
    created_at: "10/14/2023",
  },
  {
    id: 49,
    sender: 39,
    receiver: 7,
    message_content:
      "I would love to work with you on studying history. We can share notes and discuss important events.",
    thread_id: 28,
    created_at: "10/17/2023",
  },
  {
    id: 50,
    sender: 42,
    receiver: 36,
    message_content:
      "I think we can collaborate on studying math together and help each other understand complex concepts.",
    thread_id: 17,
    created_at: "10/15/2023",
  },
];

module.exports = { users, events, rsvps, messages };
